services:
  - type: web
    name: online-quiz
    env: docker
    plan: free
    region: singapore
    envVars:
      - key: DB_HOST
        value: aws-0-ap-south-1.pooler.supabase.com
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres.ojixfqxwtqutcelrzwmd
      - key: DB_PASSWORD
        value: Rahul216746
      - key: DB_PORT
        value: 6543
      - key: JAVA_OPTS
        value: -Djava.security.egd=file:/dev/./urandom
