services:
  - type: web
    name: online-quiz
    env: docker
    plan: free
    region: singapore
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: quiz-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: quiz-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: quiz-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: quiz-db
          property: password

databases:
  - name: quiz-db
    plan: free
    region: singapore
    databaseName: student
    user: rahul
